// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Enqueue(arg1) {
  return window['go']['main']['App']['Enqueue'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function Inspect(arg1) {
  return window['go']['main']['App']['Inspect'](arg1);
}

export function Jobs() {
  return window['go']['main']['App']['Jobs']();
}

export function LibraryEpisodes(arg1, arg2) {
  return window['go']['main']['App']['LibraryEpisodes'](arg1, arg2);
}

export function LibrarySeasons(arg1) {
  return window['go']['main']['App']['LibrarySeasons'](arg1);
}

export function LibrarySeries() {
  return window['go']['main']['App']['LibrarySeries']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenSeriesFolder(arg1) {
  return window['go']['main']['App']['OpenSeriesFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PreviewPath(arg1) {
  return window['go']['main']['App']['PreviewPath'](arg1);
}

export function RemoveJob(arg1) {
  return window['go']['main']['App']['RemoveJob'](arg1);
}

export function RemoveSeries(arg1) {
  return window['go']['main']['App']['RemoveSeries'](arg1);
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Session() {
  return window['go']['main']['App']['Session']();
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}
