// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AppVersion():Promise<string>;

export function Cancel(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<engine.UpdateInfo>;

export function Enqueue(arg1:engine.EnqueueRequest):Promise<Array<engine.Job>>;

export function History():Promise<Array<engine.HistoryItem>>;

export function Inspect(arg1:string):Promise<engine.InspectResult>;

export function Jobs():Promise<Array<engine.Job>>;

export function LibraryEpisodes(arg1:string,arg2:number):Promise<Array<engine.Job>>;

export function LibrarySeasons(arg1:string):Promise<Array<engine.LibrarySeason>>;

export function LibrarySeries():Promise<Array<engine.LibrarySeries>>;

export function Login(arg1:string):Promise<engine.Session>;

export function Logout():Promise<engine.Session>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSeriesFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Pause(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PreviewPath(arg1:string):Promise<void>;

export function RemoveJob(arg1:string):Promise<void>;

export function RemoveSeries(arg1:string):Promise<void>;

export function Resume(arg1:string):Promise<void>;

export function Retry(arg1:string):Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveSettings(arg1:engine.Settings):Promise<engine.Settings>;

export function Session():Promise<engine.Session>;

export function Settings():Promise<engine.Settings>;
